timezone: America/Denver
# Dependencies
markdown:       redcarpet
redcarpet:
    extensions: ['smart']

highlighter:         pygments
fenced_code_blocks:  true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            EVIL PAGE
tagline:          Evil's Programming Blog
url:              http://emperor1523.github.io/
paginate:            5
baseurl:          /

# About/contact
author:
  name:           Evil
  url:            http://www.mindviewinc.com
  email:          tonglizhei@gmail.com

